Create new network-with-security-group module.
terraform-alicloud-modules/terraform-alicloud-network-with-security-group pull request #1
Opened 2020-02-19 10:05 UTC by zql-tqy

2020-02-19 11:08 UTC, Rich-yi commented on variables.tf
> +  description = "A mapping of tags to assign to security group"
标点.

2020-02-19 11:08 UTC, Rich-yi commented on variables.tf
> +# Deprecated variables
我看你的changelog是一个新的module，参数应该不用兼容吧

2020-02-19 14:19 UTC, xiaozhu36 requested changes

2020-02-19 14:19 UTC, xiaozhu36 commented on README-CN.md
> +* [Route Entry](https://www.terraform.io/docs/providers/alicloud/r/route_entry.html)
route entry 这个参数在当前这个module中不用暴露

2020-02-19 14:19 UTC, xiaozhu36 commented on main.tf
> +  nexthop_ids       = var.nexthop_ids
最后这两个参数不用在这个module中暴露

2020-02-19 14:19 UTC, xiaozhu36 commented on outputs.tf
> +}
可用区和name要输出出来

2020-02-19 14:19 UTC, xiaozhu36 commented on outputs.tf
> +}
vpc的name

2020-02-19 14:19 UTC, xiaozhu36 commented on variables.tf
> +variable "existing_group_id" {
这个参数不用

2020-02-19 14:19 UTC, xiaozhu36 commented on variables.tf
> +variable "vpc_id" {
vpc_id 改成existing_vpc_id，并且要增加一个参数 use_existing_vpc；以后这两个参数要同时出现，计算vpc count的时候应该用 use_existing_vpc 和 create_vpc，而不是 existing_vpc_id和create_vpc。

2020-02-19 14:19 UTC, xiaozhu36 commented on outputs.tf
> +}
vpc的cidrblock 也要输出

2020-02-19 14:19 UTC, xiaozhu36 commented on outputs.tf
> +  description = "List of IDs of vswitch."
vswitch的网段也要输出

2020-02-20 00:22 UTC, xiaozhu36 approved these changes

2020-02-20 00:22 UTC, merged